// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Space.Server.Database.Context;

#nullable disable

namespace Space.Server.Database.NewSpaceMigrations
{
    [DbContext(typeof(NewSpaceContext))]
    [Migration("20230521210845_NewSpaceExternal_NewColumnAndDataTypeChange")]
    partial class NewSpaceExternal_NewColumnAndDataTypeChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Space.Server.Datamodel.DatabaseModels.NewSpace.NewSpaceCompanyDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("NewSpaceCompanies");
                });

            modelBuilder.Entity("Space.Server.Datamodel.DatabaseModels.NewSpace.NewSpaceExternalListItemDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstLaunch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Founded")
                        .HasColumnType("int");

                    b.Property<decimal?>("Funding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("HasFunding")
                        .HasColumnType("bit");

                    b.Property<string>("Launcher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Launches")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Perfomance")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PricePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("NewSpaceExternalListItems");
                });

            modelBuilder.Entity("Space.Server.Datamodel.DatabaseModels.NewSpace.NewSpaceLaunchVehicleDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("NewSpaceLaunchVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
